config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users do
    resources :kids do
      resources :websites 
       
    end
  end

  get "/login"     => "sessions#new"
  post "/login"    => "sessions#create"
  delete "/logout" => "sessions#destroy"

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :kid
  belongs_to :user
  has_many :websites
end

app/models/kid.rb
class Kid < ActiveRecord::Base
  belongs_to :user
  has_many :websites
#   has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
#   validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :kids
	has_secure_password
	# has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
 #  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/website.rb
class Website < ActiveRecord::Base
  belongs_to :kid
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController

	def index
		@kids = Kid.where user_id: current_user.id
    @user = User.find(current_user.id)
	end

	def show
    @kid = Kid.find(params[:id])
    #@websites = Website.where({ kid_id: params[:id] })
  end

  def new
    #@kid = Kid.new
    @user = User.find(params[:user_id])
    #@kid = @user.kids.new(kid_params)
  end

  def edit
  end

  def create
    @user = User.find(params[:user_id])
    @kid = @user.kids.new(kid_params)

    if @kid.save
				redirect_to user_kids_path(@user)
		else
			render :new
    end
  end

  
  private
    def kid_params
      params.require(:kid).permit(:name, :gender, :age, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
		
	end

	def create
		user = User.find_by(email: params[:login][:email])
		if user && user.authenticate(params[:login][:password])
			session[:user_id] = user.id.to_s
			redirect_to user_path(user)
		else
			render :new 
		end
	end

	def destroy
		session.delete(:user_id)
		redirect_to login_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
    @users = User.all
  end

	def new
    @user = User.new
  end

  def show
    @kids = Kid.where user_id: current_user.id
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController

def index
		@websites = Website.where kid_id: current_user.id
	end

	def show
    @user = User.find(params[:id])
    @kid = Kid.find(params[:id])
    @website = Website.find(params[:id])
  end

  def new
  	@user = current_user.id
  	@website = Website.new(kid_id: params[:kid_id])
    @kid = Kid.find(params[:kid_id])
  end

  def edit
  end

  def create
    @user = current_user.id
    @kid = Kid.find(params[:kid_id])
    @website = Website.new(website_params)
  	@website.kid_id = params[:kid_id].to_i

    if @website.save
				redirect_to user_kid_path( current_user.id, @kid )
		else
			render :new
    end
  end

  def destroy
    @user = current_user.id
    @kid = Kid.find(params[:kid_id])
    @website = Website.find(params[:id])
    @website.destroy
    redirect_to user_kid_path(@user, @kid) 
  end

  
  private
    def website_params
      params.require(:website).permit(:name, :url)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/kids/_listkids.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Websites</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kids.each do |kid| %>
      <tr>
        <td><%= kid.name %></td>
        <td><%= kid.age %></td>
        <td><%= link_to "Show", user_kid_path( current_user.id, kid ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/kids/index.html.erb
<h1>My Kids</h1>

<%= render 'listkids' %>

app/views/kids/new.html.erb
  <h2>Add a Child to your WWK Profile</h1>

<h3>New Child Info</h1>
<br>
<div class="col-sm-4 text-center">
    <%= form_for ([@user, @user.kids.new]) do |f| %>
        <ul>
            <li><%= f.label :name %>
                <%= f.text_field :name %>
            </li>
        </ul>
        <ul>
            <li><%= f.label :age %>
                <%= f.text_field :age %></li>
        </ul>
        <ul>
            <li><%= f.submit %></li>
        </ul>
    <% end %>

app/views/kids/show.html.erb
<h1><%= @kid.name %>'s Websites</h1>
<br><br>
	<div class="row">
		
			<% @kid.websites.each do |website| %>
				<div class="col-sm-6">
					<a href="http://<%= website.url %>" class="launch"><%= website.name %></a>
						
				<div class="iframeWrapper">	
					<iframe class="box1" width="500" height="320" src="http://<%= website.url %>"></iframe>
				</div>
					<br>
					<h3><%= link_to '', user_kid_website_path(@kid.user, @kid,  website),
              method: :delete, :class => 'glyphicon glyphicon-trash',
              data: { confirm: 'Are you sure?' } %></h3>
					<br>
				</div>
			<% end %>
			<br>
		
	</div>

<%# raise @kid.inspect %>
<div class="addWebsite col-sm-3">
			<h2 class="websiteBox"><%= link_to "Add a Website", new_user_kid_website_path(current_user, @kid) %></h2>
		</div>	
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
 <div class="container-fluid">
   <!-- Brand and toggle get grouped for better mobile display -->
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="/">World Wide Kid</a>
   </div>

   <!-- Collect the nav links, forms, and other content for toggling -->
   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav">
       <li><%= link_to 'WWK Users', users_path(current_user) %></li>
       <% if current_user %>
       <li><%= link_to 'Add a Child', new_user_kid_path(current_user) %></li>
       <li><%= link_to 'My Kids', user_path(current_user) %></li>
         </ul>
         <% end %>
       </li>
     </ul>
     
     <ul class="nav navbar-nav navbar-right">
       <li> 
         <% if current_user %>
             Hi <%= current_user.name %> 
         <% else %>
           <%= link_to 'Log In', login_path %> 
         </li>
         <% end %> 
         
       <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
       
     </ul>
   </div><!-- /.navbar-collapse -->
 </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>World Wide Kid</title>
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<%= image_tag "logo.jpg", class: "img-responsive logo" %>

<div class ="container">
	<%= yield %>
</div>
<br><br>
</body>
</html>

app/views/users/_main.html.erb
<h1>My WWK Personal Page</h1>

       <% if current_user %>
       <div class="boss">    
           <h2>Who's the boss?  <%= current_user.name %> is, oh yeah</h2>
       </div>
       <% else %>
         <%= link_to 'Log In', login_path %> 
       
       <% end %> 
        

app/views/users/index.html.erb
<h1>See who's using WWK...You don't want to be left out</h1>
<hr />


<table class="col-sm-6 table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h4><a href="/users/new">I WANT IN, NOW!</a></h4>

app/views/users/new.html.erb
<h1>Signing up will free you from BOOKMARK HELL!</h1>
<hr />

<section class="newUser">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 text-center">
        <h2>It will change your life...forever</h2>
        <%= form_for @user do |f| %>
          <ul>
            <li><%= f.label :name %></li>
            <li><%= f.text_field :name %></li>
          </ul>
          
          <ul>
            <li><%= f.label :email %></li>
            <li><%= f.text_field :email %></li>
          </ul>

          <ul>
            <li><%= f.label :password %></li>
            <li><%= f.password_field :password %></li>
          </ul>

          <ul>
            <li><%= f.label :password_confirmation %></li>
            <li><%= f.password_field :password_confirmation %></li>
          </ul>

          <ul class="create">
            <li><%= f.submit %></li>
          </ul>
        <% end %>
      </div>
      <div class="col-sm-5">
        <%= image_tag "bookmarks2.png", class: "img-responsive" %>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<%= render 'main' %>

<h3>My Kids</h3>

<%= render '/kids/listkids' %>

<%= link_to "Add a New Child", new_user_kid_path(current_user) %>

app/views/websites/index.html.erb
<h1>website index page</h1>

<%= link_to "Add", new_user_kid_website_path %>

app/views/websites/new.html.erb
 <h2>Add a website to your Child's Profile</h1>

<h3>New Website</h1>



<div class="row">
      <div class="col-sm-4 text-center">
        <h2>Type it in & Tee it up</h2>
        <%= form_for ([:user, :kid, @website]) do |f| %>
          <ul>
            <li><%= f.label :name %></li>
            <li><%= f.text_field :name %></li>
          </ul>
          
          <ul>
            <li><%= f.label :url %></li>
            <li><%= f.text_field :url %></li>
          </ul>
          <ul>
            <li><%= f.submit %></li>
          </ul>
        <% end %>
      </div>
</div>

app/views/websites/show.html.erb
<h1>Success! This website is in your child's profile</h1>


<p><%= @website.name %></p>
<p><%= @website.url %></p>

<%= button_to "Add a Website", new_user_kid_website_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<head>
	<meta charset="utf-8">

<h1>Welcome to World Wide Kid</h1>
	<hr />

		<div class="container">
			<div class="row">
				<div class="col-sm-6">
					<%= image_tag "girl_surfing_net.jpg", class: "img-responsive" %>
				</div>
				<div class="col-sm-6 text-center">
					<h2>Does this look familiar?</h2>
					<h4>
						Then this is the website for you.  Never again get lost in that endless list of bookmarks at an inopportune moment!
					</h4>
					<h3>Create an account <a href="/users/new">here</a> to get started.</h3>

					<h3>Already a WWK User?  <a href="/login">Login here</a></h3>
				</div>
			</div>




</body>
</html>